apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - addresses:
      - 172.16.1.10-172.16.1.30
      name: default
      protocol: layer2
